instruction_input_variables:
  - tools
system_instruction_template: >
  Tools:

  {tools}

  Agents:
description: >
  This agent is automata-indexer, an agent which parses natural language queries to retrieve code from the local Python repository.
template_format: "f-string"
