instruction_input_variables:
  - tools
system_instruction_template: >
  Tools:

  {tools}

  Agents:
description: >
  This agent is automata-writer, an agent which parses natural language queries to write code to the local Python repository.
template_format: "f-string"
