input_variables:
  - initializer_dummy_tool
  - user_input_instructions
initial_messages:
  - role: "assistant"
    content: >
      - thoughts
        - I will begin by initializing myself.
      - actions
        - agent_query_0
          - agent_name
            - {initializer_dummy_tool}
          - agent_instruction
            - Hello, I am Automata, OpenAI's most skilled coding system. How may I assist you today?
  - role: "user"
    content: >
      - observation:
        - agent_output_0
          - task_0
          - Please carry out the following instruction {user_input_instructions}.
