name: Check Import Sorting

on: [pull_request]

jobs:
  import-sorting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort

      - name: Check import sorting
        run: |
          isort --check-only --diff .
